{{- if .Values.server.notary.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dctna.fullname" . }}-notary-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dctna.labels" . | nindent 4 }}
type: Opaque
data:
  basic: {{ print .Values.server.notary.auth.username ":" .Values.server.notary.auth.password | b64enc | b64enc }} # double encoding as we need the value as base64
{{- end }}
