apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dctna.fullname" . }}-notary-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dctna.labels" . | nindent 4 }}
data:
  config.json: |-
  {{- .Values.server.notary.config | toPrettyJson | nindent 4}}
