apiVersion: v1
kind: Service
metadata:
  name: {{ include "dctna.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dctna.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.server.service.httpsPort }}
      targetPort: https
      name: https
  selector:
    {{- include "dctna.selectorLabels" . | nindent 4 }}
    component: server
