apiVersion: v1
kind: Service
metadata:
  name: {{ include "dctna.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dctna.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dctna.selectorLabels" . | nindent 4 }}
    component: web
