name: Continuous Integration

on: [push, pull_request]

jobs:
  lint-chart:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup chart-testing
        uses: helm/chart-testing-action@v2.1.0
        with:
          version: v3.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch main)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: |
          ct lint --debug \
            --target-branch main

      - name: Run helm-docs
        run: .github/helm-docs.sh

    outputs:
      changed: ${{ steps.list-changed.outputs.changed }}

  kubeval-chart:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    needs:
      - lint-chart
    strategy:
      matrix:
        k8s:
          - v1.15.7
          - v1.16.4
          - v1.17.4
          - v1.18.1
          - v1.19.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh

  test:
    name: Test
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    needs:
      - lint-chart

    strategy:
      fail-fast: false
      matrix:
        k8s:
          - v1.19.11
          - v1.20.7
          - v1.21.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup chart-testing
        uses: helm/chart-testing-action@v2.1.0
        with:
          version: v3.3.1

      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.7.0
        # Only build a kind cluster if there are chart changes to test.
        if: needs.lint-chart.outputs.changed == 'true'
        with:
          version: v0.11.1
          node_image: kindest/node:${{ matrix.k8s }}
          config: .github/kind/conf/kind-config.yaml
          log_level: debug

      - name: Run chart-testing (install)
        run: |
          ct install --debug \
            --target-branch main \
            --exclude-deprecated
