name: Release Charts

on:
  push:
    branches:
      - master
      - feature/release

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        with:
          charts_dir: ..
        env:
          CR_TOKEN: '${{ secrets.CR_TOKEN }}'
